version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../DB/database.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./Backend
    container_name: backend
    restart: on-failure  
    ports:
      - "3000:3000"
    depends_on:
      - mysql  
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: database
    command: >
      sh -c "sleep 15 && npm run start:prod"

volumes:
  mysql-data: